#!/usr/bin/env python3
"""Embed the FMPMDE YM2608 rhythm WAVs (songs/touhou_pc98/player/2608_*.wav) as
a const int16 PCM table for the on-device drum voices. The YM2608 has no ADPCM
rhythm ROM available here, so we play these 44.1kHz mono recordings instead
(what FMPMDE does), resampled to the mix rate at playback time.

Rhythm bit order (reg 0x10 bits 0..5): BD SD TOP HH TOM RIM."""
import struct, sys, os

SRC = os.path.join(os.path.dirname(__file__), "..", "..", "songs", "touhou_pc98", "player")
# voice index -> wav basename (YM2608 rhythm bit order)
VOICES = ["bd", "sd", "top", "hh", "tom", "rim"]

def read_wav(path):
    with open(path, "rb") as f:
        d = f.read()
    assert d[:4] == b"RIFF" and d[8:12] == b"WAVE", path
    pos = 12
    fmt = None
    data = None
    while pos + 8 <= len(d):
        cid = d[pos:pos+4]; sz = struct.unpack_from("<I", d, pos+4)[0]; pos += 8
        if cid == b"fmt ":
            af, ch, sr, br, ba, bps = struct.unpack_from("<HHIIHH", d, pos)
            fmt = (af, ch, sr, bps)
        elif cid == b"data":
            data = d[pos:pos+sz]
        pos += sz + (sz & 1)
    assert fmt and data, path
    af, ch, sr, bps = fmt
    assert af == 1 and ch == 1 and bps == 16, (path, fmt)
    n = len(data) // 2
    return sr, list(struct.unpack_from("<%dh" % n, data, 0))

def main():
    out = sys.argv[1] if len(sys.argv) > 1 else "src/opna/opna_drum_pcm.h"
    rate = None
    arrays = []
    total = 0
    for name in VOICES:
        sr, samples = read_wav(os.path.join(SRC, "2608_%s.wav" % name))
        if rate is None: rate = sr
        assert sr == rate, "mixed sample rates"
        arrays.append((name, samples))
        total += len(samples)
    with open(out, "w") as f:
        f.write("/* Generated by firmware/tools/gen_drumpcm.py -- do not edit.\n")
        f.write("   FMPMDE YM2608 rhythm samples (BD SD TOP HH TOM RIM), %d Hz mono.\n" % rate)
        f.write("   %d samples total = %d bytes of flash. */\n" % (total, total*2))
        f.write("#ifndef PFM_OPNA_DRUM_PCM_H\n#define PFM_OPNA_DRUM_PCM_H\n#include <stdint.h>\n\n")
        f.write("#define PFM_DRUM_PCM_RATE %d\n\n" % rate)
        for name, samples in arrays:
            f.write("static const int16_t drum_pcm_%s[%d] = {\n" % (name, len(samples)))
            for i in range(0, len(samples), 16):
                f.write(" " + ",".join("%d" % s for s in samples[i:i+16]) + ",\n")
            f.write("};\n")
        f.write("\nstatic const struct { const int16_t *data; unsigned len; } drum_pcm[6] = {\n")
        for name, samples in arrays:
            f.write("  { drum_pcm_%s, %d },\n" % (name, len(samples)))
        f.write("};\n\n#endif\n")
    print("wrote %s: %d samples, %d bytes (%.1f KB flash)" % (out, total, total*2, total*2/1024))

if __name__ == "__main__":
    main()
