#!/usr/bin/env python3
"""Embed PMD .M songs into flash as a C array + index table.

The Primer2 build has no SD driver yet, so tracks live in flash. The PMD driver
writes loop counters back into the sequence data, so each song is copied into a
RAM buffer before playing (board_storage_load).
"""
import os, sys, glob

ROOT = "songs/touhou_pc98"
OUT = sys.argv[1] if len(sys.argv) > 1 else "firmware/gen/songs.h"
BUDGET = int(sys.argv[2]) if len(sys.argv) > 2 else 220 * 1024
MAX_ONE = 24 * 1024  # must fit the RAM song buffer

GAMES = {
    "TH1": "東方靈異伝",
    "TH2": "東方封魔録",
    "TH3": "東方夢時空",
    "TH4": "東方幻想郷",
    "TH5": "東方怪綺談",
}


def sjis_escape(s):
    return "".join(f"\\x{b:02x}" for b in s.encode("shift_jis"))


paths = sorted(glob.glob(os.path.join(ROOT, "**", "*.M"), recursive=True))
chosen, total = [], 0
for p in paths:
    n = os.path.getsize(p)
    if n > MAX_ONE or total + n > BUDGET:
        continue
    chosen.append((p, n))
    total += n

os.makedirs(os.path.dirname(OUT), exist_ok=True)
with open(OUT, "w") as f:
    f.write("#ifndef PFM_SONGS_H\n#define PFM_SONGS_H\n#include <stdint.h>\n")
    f.write("/* Auto-generated by firmware/tools/gen_songs.py -- PMD .M songs in flash. */\n")
    f.write(f"#define SONG_COUNT {len(chosen)}\n")
    f.write(f"#define SONG_MAX_LEN {max(n for _, n in chosen)}\n\n")

    f.write("static const uint8_t song_blob[] = {\n")
    off = 0
    offsets = []
    for p, n in chosen:
        data = open(p, "rb").read()
        offsets.append((off, len(data)))
        off += len(data)
        for i in range(0, len(data), 16):
            f.write("  " + ",".join(f"0x{b:02x}" for b in data[i:i+16]) + ",\n")
    f.write("};\n\n")

    f.write("struct song_entry { uint32_t off, len; const char *name; const char *group; };\n")
    f.write("static const struct song_entry song_table[SONG_COUNT] = {\n")
    for (p, _), (o, l) in zip(chosen, offsets):
        name = os.path.splitext(os.path.basename(p))[0]
        key = os.path.basename(os.path.dirname(p))[:3].upper()
        grp = GAMES.get(key, "")
        f.write(f'  {{{o}u, {l}u, "{name}", "{sjis_escape(grp)}"}},\n')
    f.write("};\n#endif\n")

print(f"wrote {OUT}: {len(chosen)} songs, {total} bytes ({total/1024:.1f} KB) of flash")
