#!/usr/bin/env python3
"""Emit hardcoded Japanese UI strings as Shift-JIS byte escapes, so the C source
stays ASCII/UTF-8-safe while the runtime bytes are valid CP932 for our renderer."""
import sys

OUT = sys.argv[1] if len(sys.argv) > 1 else "firmware/gui/ui_strings.h"

STRINGS = {
    "UI_TITLE":       "東方 PC-98 FM",
    "UI_SUBTITLE":    "曲を選択してください",
    "UI_NOWPLAYING":  "再生中",
    "UI_HINT":        "上下:選択  中央:再生",
    "UI_RENDERING":   "レンダリング中...",
    "UI_DONE":        "完了",
}


def esc(s):
    return "".join(f"\\x{b:02x}" for b in s.encode("shift_jis"))


with open(OUT, "w") as f:
    f.write("#ifndef PFM_UI_STRINGS_H\n#define PFM_UI_STRINGS_H\n")
    f.write("/* Auto-generated by firmware/tools/gen_ui_strings.py (Shift-JIS bytes). */\n")
    for k, v in STRINGS.items():
        f.write(f'#define {k} "{esc(v)}" /* {v} */\n')
    f.write("#endif\n")
print(f"wrote {OUT}")
