#!/usr/bin/env python3
"""Generate a packed bitmap font header from a monospace TTF.
Renders ASCII 0x20..0x7E into a fixed WxH cell (1 bpp, MSB = leftmost pixel).
Also writes a preview PNG for visual sanity checking."""
import sys
from PIL import Image, ImageFont, ImageDraw

TTF = "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf"
W, H = 6, 10          # cell size in pixels
PT = 11               # font point size (tuned to fill the cell)
X_OFF, Y_OFF = -1, -1 # nudge glyph within the cell
FIRST, LAST = 0x20, 0x7E
OUT_H = sys.argv[1] if len(sys.argv) > 1 else "firmware/gui/font.h"
OUT_PNG = sys.argv[2] if len(sys.argv) > 2 else "build-fw/font_preview.png"

font = ImageFont.truetype(TTF, PT)

glyphs = {}
for c in range(FIRST, LAST + 1):
    img = Image.new("L", (W, H), 0)
    d = ImageDraw.Draw(img)
    d.text((X_OFF, Y_OFF), chr(c), fill=255, font=font)
    rows = []
    for y in range(H):
        b = 0
        for x in range(W):
            if img.getpixel((x, y)) > 110:
                b |= 1 << (7 - x)
        rows.append(b)
    glyphs[c] = rows

with open(OUT_H, "w") as f:
    f.write("#ifndef PFM_FONT_H\n#define PFM_FONT_H\n#include <stdint.h>\n")
    f.write("/* Auto-generated by firmware/tools/genfont.py from DejaVuSansMono. */\n")
    f.write(f"#define FONT_W {W}\n#define FONT_H {H}\n")
    f.write(f"#define FONT_FIRST {FIRST}\n#define FONT_LAST {LAST}\n")
    f.write(f"static const uint8_t font_data[{LAST-FIRST+1}][{H}] = {{\n")
    for c in range(FIRST, LAST + 1):
        vals = ",".join(f"0x{b:02x}" for b in glyphs[c])
        ch = chr(c) if c != 0x5C else "backslash"
        f.write(f"  {{{vals}}}, /* {c:#04x} '{ch if c!=0x27 else chr(39)}' */\n")
    f.write("};\n#endif\n")

# preview: render a sample string large for eyeballing
sample = "ABCDEFG abcdefg 0123456789 Th01_01.M ()-_./:#"
scale = 6
pv = Image.new("RGB", (len(sample) * W * scale, H * scale), (20, 20, 30))
for i, ch in enumerate(sample):
    c = ord(ch)
    if c < FIRST or c > LAST:
        continue
    rows = glyphs[c]
    for y in range(H):
        for x in range(W):
            if rows[y] & (1 << (7 - x)):
                for dy in range(scale):
                    for dx in range(scale):
                        pv.putpixel((i * W * scale + x * scale + dx, y * scale + dy),
                                    (230, 230, 120))
pv.save(OUT_PNG)
print(f"wrote {OUT_H} ({LAST-FIRST+1} glyphs, {W}x{H}) and preview {OUT_PNG}")
