#!/usr/bin/env python3
"""Generate a Shift-JIS (CP932 / JIS X 0208) bitmap font header from the Misaki
gothic 8x8 BDF (public domain, littlelimit.net).

Layout:
  hankaku[0x20..0xDF][8]  : half-width 4x8 glyphs (ASCII + half-width katakana),
                            one byte per row, MSB = leftmost pixel (4 bits used).
  zenkaku[47*188][8]      : full-width 8x8 glyphs, indexed by the packed SJIS
                            code  idx = lead*188 + trail  where
                              lead  = b1<=0x9F ? b1-0x81 : b1-0xC1
                              trail = b2<=0x7E ? b2-0x40 : b2-0x41
The C renderer (gfx.c) reproduces the same index arithmetic at runtime.
"""
import sys
from PIL import Image, ImageFont, ImageDraw

BDF = sys.argv[1] if len(sys.argv) > 1 else "third_party/misaki/misaki_gothic.bdf"
OUT = sys.argv[2] if len(sys.argv) > 2 else "firmware/gui/font_sjis.h"
PREVIEW = sys.argv[3] if len(sys.argv) > 3 else "build-fw/font_sjis_preview.png"

font = ImageFont.truetype(BDF, 8)


def render(ch, w, h=8):
    img = Image.new("L", (w, h), 0)
    ImageDraw.Draw(img).text((0, 0), ch, fill=255, font=font)
    px = img.load()
    rows = []
    for y in range(h):
        b = 0
        for x in range(w):
            if px[x, y] > 110:
                b |= 1 << (7 - x)
        rows.append(b)
    return rows


# half-width table: 0x20..0xDF
HANK_FIRST, HANK_LAST = 0x20, 0xDF
hank = {}
for b in range(HANK_FIRST, HANK_LAST + 1):
    ch = None
    if 0x20 <= b <= 0x7E:
        ch = chr(b)
    elif 0xA1 <= b <= 0xDF:
        try:
            ch = bytes([b]).decode("shift_jis")  # single-byte half-width kana
        except Exception:
            ch = None
    hank[b] = render(ch, 4) if ch else [0] * 8

# full-width table
NLEAD, NTRAIL = 47, 188
zen = [[0] * 8 for _ in range(NLEAD * NTRAIL)]
nfull = 0
for b1 in list(range(0x81, 0xA0)) + list(range(0xE0, 0xF0)):
    lead = b1 - 0x81 if b1 <= 0x9F else b1 - 0xC1
    for b2 in list(range(0x40, 0x7F)) + list(range(0x80, 0xFD)):
        trail = b2 - 0x40 if b2 <= 0x7E else b2 - 0x41
        try:
            ch = bytes([b1, b2]).decode("shift_jis")
        except Exception:
            continue
        if not ch:
            continue
        rows = render(ch, 8)
        if any(rows):
            zen[lead * NTRAIL + trail] = rows
            nfull += 1

with open(OUT, "w") as f:
    f.write("#ifndef PFM_FONT_SJIS_H\n#define PFM_FONT_SJIS_H\n#include <stdint.h>\n")
    f.write("/* Auto-generated by firmware/tools/genfont_sjis.py from Misaki gothic 8x8\n"
            "   (public domain, littlelimit.net). Shift-JIS / JIS X 0208. */\n")
    f.write("#define SJIS_CELL_H 8\n")
    f.write(f"#define SJIS_HANK_FIRST 0x{HANK_FIRST:02x}\n")
    f.write(f"#define SJIS_HANK_LAST  0x{HANK_LAST:02x}\n")
    f.write(f"#define SJIS_ZEN_NLEAD  {NLEAD}\n#define SJIS_ZEN_NTRAIL {NTRAIL}\n")
    f.write(f"static const uint8_t sjis_hankaku[{HANK_LAST-HANK_FIRST+1}][8] = {{\n")
    for b in range(HANK_FIRST, HANK_LAST + 1):
        f.write("  {" + ",".join(f"0x{x:02x}" for x in hank[b]) + f"}}, /* 0x{b:02x} */\n")
    f.write("};\n")
    f.write(f"static const uint8_t sjis_zenkaku[{NLEAD*NTRAIL}][8] = {{\n")
    for i in range(NLEAD * NTRAIL):
        f.write("  {" + ",".join(f"0x{x:02x}" for x in zen[i]) + "},\n")
    f.write("};\n#endif\n")

# preview
sample = "pocket-fmdsp  東方PC-98  幻想郷  ｶﾅ 0123"
scale = 6
pv = Image.new("RGB", (len(sample) * 8 * scale, 8 * scale), (18, 18, 28))
x = 0
for ch in sample:
    rows = render(ch, 8)
    w = 8 if ord(ch) > 0x7F and ord(ch) not in range(0xFF61, 0xFFA0) else 4
    for y in range(8):
        for xx in range(w):
            if rows[y] & (1 << (7 - xx)):
                for dy in range(scale):
                    for dx in range(scale):
                        pv.putpixel((x + xx * scale + dx, y * scale + dy), (235, 235, 130))
    x += w * scale
pv.save(PREVIEW)
print(f"wrote {OUT}: {HANK_LAST-HANK_FIRST+1} half-width, {nfull} full-width glyphs; preview {PREVIEW}")
